name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group:
          - Core
        version:
          - '1'
          - '1.8'
    steps:
      - uses: actions/checkout@v2
      - name: Build R language
        uses: r-lib/actions/setup-r@v2
      - name: Setup R_HOME environment variable
        run: echo "LD_LIBRARY_PATH=$(R RHOME)/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      - name: Install curl package
        run: |
          sudo apt-get install -y curl python3-pycurl libcurl4-openssl-dev
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: |
                  ${{secrets.SSH_PRIVATE_KEY_JGENDUNIV}}
      - name: Download and install R packages - readr
        run: | 
          R -e 'install.packages("readr")'
      - name: Download and install R packages - forecast
        run: | 
          R -e 'install.packages("forecast")'
      - name: Download and install R packages - data.table
        run: | 
          R -e 'install.packages("data.table")'
      - name: Install Julia language
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Install JuliaGendUniv_Types private repo
        run: julia --project -e 'using Pkg; Pkg.develop(; url="git@github.com:university-gender-evolution/JuliaGendUniv_Types.jl.git")'
      - name: Build JuliaGendUniv package
        uses: julia-actions/julia-buildpkg@v1
      - name: Download UM datafile for testing
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'university-gender-evolution/JuliaGendUniv.jl'
          version: 'tags/0.1.0'
          file: 'michigan1979to2009_wGender.dta'
          target: 'test/michigan1979to2009_wGender.dta'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check file download was successful
        run: |
          cd test
          ls -lah
          cd ..
      - name: Build RCall package
        run: |
          julia --project=@. -e 'import Pkg; Pkg.build("RCall");' 
      - name: Run julia tests
        uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
