name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group:
          - Core
        version:
          - '1'
          - '1.8'
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install curl package
        run: |
          sudo apt-get install -y curl python3-pycurl libcurl4-openssl-dev
      - name: Download and install R packages - readr
        run: | 
          R -e 'install.packages("readr")'
      - name: Download and install R packages - forecast
        run: | 
          R -e 'install.packages("forecast")'
      - name: Download and install R packages - data.table
        run: | 
          R -e 'install.packages("data.table")'
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - name: Download data for test from private repo
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'university-gender-evolution/JuliaGendUniv.jl'
          version: 'tags/0.1.0'
          file: 'michigan1979to2009_wGender.dta'
          target: 'test/michigan1979to2009_wGender.dta'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: (DEBUG) Check file download was successful
        run: |
          cd test
          ls -lah
          cd ..
      - name: (DEBUG) Build RCall package
        run: |
          julia --project=@. -e 'import Pkg; Pkg.build("RCall")' 
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
